In [1]:
import numpy as np

**Question_1**

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
#part_a
arr+2

array([3, 4, 5, 6, 7])

In [4]:
#part_b
arr*3

array([ 3,  6,  9, 12, 15])

In [5]:
#part_c
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

**Question_2**

In [6]:
#part_a
arr = np.array([1, 2, 3, 6, 4, 5])
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [7]:
#part_b
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(f"Most frequent element in x: {x[np.bincount(x).max()]}")
print(f"Count: {np.bincount(x).max()}\n")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print(f"Most frequent element in y: {y[np.bincount(y).max()]}")
print(f"Count: {np.bincount(y).max()}\n")

Most frequent element in x: 1
Count: 5

Most frequent element in y: 2
Count: 3



**Question_3**

In [8]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


**Question_4**

In [9]:
manmeet=np.linspace(10,100,25)
print("Dimension:",manmeet.ndim)
print("Shape:",manmeet.shape)
print("Total elements:",manmeet.size)
print("Datatypes",manmeet.dtype)
print("Size in Bytes:",manmeet.nbytes)
print(manmeet.reshape(25,1))
print("No,We cannot do same with T attribute because it only works on arrays with dimension of greater than or equal to 2")

Dimension: 1
Shape: (25,)
Total elements: 25
Datatypes float64
Size in Bytes: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
No,We cannot do same with T attribute because it only works on arrays with dimension of greater than or equal to 2


**Question_5**

In [10]:
ucs420_manmeet=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
print("Mean:",ucs420_manmeet.mean())
print("Median:",np.median(ucs420_manmeet))
print("Max:",ucs420_manmeet.max())
print("Min:",ucs420_manmeet.min())
print("Unique Elements:",np.unique(ucs420_manmeet))
reshaped_ucs420_manmeet=np.array(ucs420_manmeet.reshape(4,3))
print("Renamed array and Resaped array:\n",reshaped_ucs420_manmeet)
resized_ucs420_manmeet=np.resize(reshaped_ucs420_manmeet,(2,3))
print("Resized and Renamed array:\n",resized_ucs420_manmeet)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Renamed array and Resaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized and Renamed array:
 [[10 20 30]
 [40 50 60]]
